name: Populate README

on:
  push:
    paths:
      - '20**/*.R'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Debug Find Command
      run: |
        pwd
        find . -type d -regex "./[0-9]\{4\}" 
        find ./ -type d -regex "./[0-9]\{4\}" 

    - name: Generate Script List Section
      id: generate-section
      run: |
        echo "" > script_list.md
        for dir in $(find ./ -type d -regex "./[0-9]\{4\}"); do
          echo "## $dir" >> script_list.md
          # Use -maxdepth 1 to look only in the top level and sort for ordering
          for file in $(find $dir -maxdepth 1 -name "*.R" | sort); do
            # Extract the header using sed
            header=$(sed -n '1p' $file | sed 's/^# \(.*\) ----/\1/')
            echo "- [$header]($file)" >> script_list.md
          done
        done
        cat script_list.md

    - name: Update README.md
      run: |
        awk 'NR==FNR { print; if ($0 ~ /Script List/) exit; next } 1' README.md script_list.md > temp.md && mv temp.md README.md
        cat README.md

    - name: Commit and push if it's not up-to-date
      run: |
        git diff
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || (git add README.md; git commit -m "AUTO Update README.md"; git push origin HEAD:main --follow-tags)
