name: Populate README

on:
  push:
    paths:
      - '20**/*.R'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate Script List Section
      id: generate-section
      run: |
        echo "Script List" > script_list.md
        for dir in $(find . -type d -regex "./[0-9]\{4\}"); do
          echo "## $dir" >> script_list.md
          # Use -maxdepth 1 to look only in the top level and sort for ordering
          for file in $(find $dir -maxdepth 1 -name "*.R" | sort); do
            # Extract the header using sed
            header=$(sed -n '1p' $file | sed 's/^# \(.*\) ----/\1/')
            echo "- [$header]($file)" >> script_list.md
          done
        done

    - name: Update README.md
      run: |
        awk 'NR==FNR { if ($0 ~ /Script List/) exit; print; next } 1' README.md script_list.md > temp.md && mv temp.md README.md

    - name: Commit and push if changed
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md with script list" && git push)
